### ISSUE TITLE
Passing an invalid `config` results in unclear error message

### ISSUE THREAD

**Issue by nathanleiby** [Clever/ARCHIVED-aviator#32]
Updating the pong `aviator.yml` to have two setups:

``` yml
pong:
  setups:
    default:
      publish:
       server: "localhost:8080"
      cmd: ./server.sh
   staging:
     publish:
       server: "staging-pong-server.example.com"
```

and running `aviator ping`, then passing an invalid config `aa`

```
$ aviator ping
Configuration options for 'pong':
 -    default : localhost:8080 "./server.sh"
 -    staging : staging-pong-server.example.com
Config for pong?
aa # <--- pass an invalid config
```

Results in an unclear error

```
Error: Your environment is missing the following environment variables:
'SERVER' required by service 'ping'.  Value published as 'pong.server'
```

With just two services this is easier to catch, but with nested services this might be harder to debug.
